### ISSUE TITLE
Mark Task done/undone

### ISSUE THREAD

**Issue by kanchan-salame** [bartoszrychlicki/GoodPoints-Front#10]
- Create new activityType from taskType
- `reward` field should be number
- `description` field should be String
- `taskType` Should be object of taskType

**Comment by bartoszrychlicki** [comment]
You don't create activityType from taskType. You create activityType that is connected to taskType. (many-to-one). 
You create activity based on activityType.

**Comment by bartoszrychlicki** [comment]
The architecture diagram has more info.
